const products = [
  {
    id: 1,
    name: "iPhone 15 Pro",
    category: "Smartphone",
    brand: "Apple",
    price: 999,
    rating: 4.7,
    image: "📱",
    features: {
      display: '6.1" Super Retina XDR',
      processor: "A17 Pro",
      storage: "128GB/256GB/512GB/1TB",
      camera: "48MP Main + 12MP Ultra Wide + 12MP Telephoto",
      battery: "Up to 23 hours video",
      os: "iOS 17",
      connectivity: "5G, WiFi 6E, Bluetooth 5.3",
      water_resistance: "IP68",
      weight: "187g",
    },
  },
  {
    id: 2,
    name: "Samsung Galaxy S24 Ultra",
    category: "Smartphone",
    brand: "Samsung",
    price: 1199,
    rating: 4.6,
    image: "📱",
    features: {
      display: '6.8" Dynamic AMOLED 2X',
      processor: "Snapdragon 8 Gen 3",
      storage: "256GB/512GB/1TB",
      camera: "200MP Main + 50MP Periscope + 10MP Telephoto + 12MP Ultra Wide",
      battery: "5000mAh, up to 28 hours video",
      os: "Android 14",
      connectivity: "5G, WiFi 7, Bluetooth 5.3",
      water_resistance: "IP68",
      weight: "232g",
    },
  },
  {
    id: 3,
    name: "MacBook Air M3",
    category: "Laptop",
    brand: "Apple",
    price: 1099,
    rating: 4.8,
    image: "💻",
    features: {
      display: '13.6" Liquid Retina',
      processor: "Apple M3",
      storage: "256GB/512GB/1TB/2TB SSD",
      camera: "1080p FaceTime HD",
      battery: "Up to 18 hours",
      os: "macOS Sonoma",
      connectivity: "WiFi 6E, Bluetooth 5.3",
      water_resistance: "N/A",
      weight: "1.24kg",
    },
  },
  {
    id: 4,
    name: "Dell XPS 13",
    category: "Laptop",
    brand: "Dell",
    price: 999,
    rating: 4.4,
    image: "💻",
    features: {
      display: '13.4" FHD+ InfinityEdge',
      processor: "Intel Core i7-1355U",
      storage: "512GB/1TB SSD",
      camera: "720p HD",
      battery: "Up to 12 hours",
      os: "Windows 11",
      connectivity: "WiFi 6E, Bluetooth 5.2",
      water_resistance: "N/A",
      weight: "1.27kg",
    },
  },
  {
    id: 5,
    name: 'iPad Pro 12.9"',
    category: "Tablet",
    brand: "Apple",
    price: 1099,
    rating: 4.7,
    image: "📱",
    features: {
      display: '12.9" Liquid Retina XDR',
      processor: "Apple M2",
      storage: "128GB/256GB/512GB/1TB/2TB",
      camera: "12MP Wide + 10MP Ultra Wide",
      battery: "Up to 10 hours",
      os: "iPadOS 17",
      connectivity: "WiFi 6E, Bluetooth 5.3, Optional 5G",
      water_resistance: "N/A",
      weight: "682g",
    },
  },
  {
    id: 6,
    name: "Surface Pro 9",
    category: "Tablet",
    brand: "Microsoft",
    price: 999,
    rating: 4.3,
    image: "📱",
    features: {
      display: '13" PixelSense Flow',
      processor: "Intel Core i5/i7 12th Gen",
      storage: "128GB/256GB/512GB/1TB SSD",
      camera: "5MP Front + 10MP Rear",
      battery: "Up to 15.5 hours",
      os: "Windows 11",
      connectivity: "WiFi 6E, Bluetooth 5.1, Optional 5G",
      water_resistance: "N/A",
      weight: "879g",
    },
  },
  {
    id: 7,
    name: "Dell XPS 13",
    category: "Laptop",
    brand: "Dell",
    price: 999,
    rating: 4.4,
    image: "💻",
    features: {
      display: '13.4" FHD+ InfinityEdge',
      processor: "Intel Core i7-1355U",
      storage: "512GB/1TB SSD",
      camera: "720p HD",
      battery: "Up to 12 hours",
      os: "Windows 11",
      connectivity: "WiFi 6E, Bluetooth 5.2",
      water_resistance: "N/A",
      weight: "1.27kg",
    },
  },
  {
    id: 8,
    name: 'iPad Pro 12.9"',
    category: "Tablet",
    brand: "Apple",
    price: 1099,
    rating: 4.7,
    image: "📱",
    features: {
      display: '12.9" Liquid Retina XDR',
      processor: "Apple M2",
      storage: "128GB/256GB/512GB/1TB/2TB",
      camera: "12MP Wide + 10MP Ultra Wide",
      battery: "Up to 10 hours",
      os: "iPadOS 17",
      connectivity: "WiFi 6E, Bluetooth 5.3, Optional 5G",
      water_resistance: "N/A",
      weight: "682g",
    },
  },
];
export default products;
